default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: password

development:
  <<: *default
  database: infra_development

test:
  <<: *default
  database: infra_test

production:
  <<: *default
  database: infra_production
  username: root
  password: password # ansibleで設定したpassword
  host: test-db.c9n6i9gkny3s.ap-northeast-1.rds.amazonaws.com # RDSのエンドポイント
